next iteration

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,7 +1,12 @@
 image: alpine
 
+#after_script:
+#  - rm -rf ./defectdojo-infrastructure.env
+
 stages:
-  - security
+  - trivy_scan
+  - create_engagement
+  - upload_results
 
 variables:
   DEFECTDOJO_URL: "http://host.docker.internal:8080/api/v2"
@@ -11,35 +16,99 @@ variables:
   DEFECTDOJO_SCAN_VERIFIED: "true"
   DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: "true"
   DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
-  DEFECTDOJO_SCAN_TYPE: "Trivy Scan"
-  DEFECTDOJO_ENGAGEMENTID: "6"
-  DEFECTDOJO_SCAN_FILE: "results.json"
-  IMAGE: "api-gateway"
-  IMAGE_TAG: "latest"
+  DEFECTDOJO_SCAN_FILE_NAME: "gl-container-scanning-report.json"
+  DEFECTDOJO_SCAN_DIRECTORY: "./scanresults/${DEFECTDOJO_SCAN_FILE_NAME}"
 
 before_script:
-    - apk add --no-cache curl jq coreutils
-    - TODAY=$(date +%Y-%m-%d)
+  - apk add --update --no-cache curl jq coreutils findutils
+  - TODAY=$(date +%Y-%m-%d)
+  - ENDDAY=$(date +%Y-%m-%d)
 
-trivy_scan:
-  stage: security
-  allow_failure: false
-  script:
-    - trivy image -f json -o results.json "$IMAGE:$IMAGE_TAG" 
+#trivy_scan:
+#  stage: trivy_scan
+#  image: docker:stable
+#  before_script:
+#    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
+#    - echo $TRIVY_VERSION
+#    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
+#    - mkdir -p ./scanresults/trivy
+#  services:
+#    - name: docker:dind
+#      entrypoint: ["env", "-u", "DOCKER_HOST"]
+#      command: ["dockerd-entrypoint.sh"]
+#  variables:
+#    DOCKER_HOST: tcp://docker:2375/
+#    DOCKER_DRIVER: overlay2
+#    # See https://github.com/docker-library/docker/pull/166
+#    DOCKER_TLS_CERTDIR: ""
+#    DEFECTDOJO_SCAN_FILE_NAME: "trivy-container-scanning-report.json"
+#    DEFECTDOJO_SCAN_FILE_DIRECTORY: "./scanresults/trivy"
+#  allow_failure: false
+#  script:
+#    - ./trivy image -f json -o "${DEFECTDOJO_SCAN_FILE_DIRECTORY}/${DEFECTDOJO_SCAN_FILE_NAME}" ghcr.io/domehahn/api-gateway:latest
+#  cache:
+#    paths:
+#      - .trivycache/
+#  artifacts:
+#    paths:
+#     - gl-container-scanning-report.json
 
-defectdojo_upload_results:
-  stage: .post
-  allow_failure: false
+defectdojo_create_engagement:
+  stage: create_engagement
+  allow_failure: true
   script:
+    - source ./scripts/extract.sh
+    - |
+      SEARCH_DIR="."
+      FILE_NAME="defectdojo-infrastructure.env"
+      FILE_PATH=$(find "$SEARCH_DIR" -name "$FILE_NAME" -print -quit)
+      if [[ -n "$FILE_PATH" ]]; then
+        echo "File found: $FILE_PATH"
+        source "$FILE_PATH"
+      else
+        echo "File not found: $FILE_NAME"
+      exit 1
+      fi
+    - >
+      run_command "curl -s -D - -d '' --request POST \"${DEFECTDOJO_URL}/engagements/\" \
+        --header \"Authorization: Token ${DEFECTDOJO_TOKEN}\" \
+        --header 'Content-Type: application/json' \
+        --data-raw '{
+          \"name\": \"Initial Scan\",
+          \"description\": \"Initial Scan result\",
+          \"version\": \"1.0\",
+          \"first_contacted\": \"${TODAY}\",
+          \"target_start\": \"${TODAY}\",
+          \"target_end\": \"${ENDDAY}\",
+          \"lead\": \"${DEFECTDOJO_USER_ID}\",
+          \"engagement_type\": \"CI/CD\",
+          \"product\": \"${DEFECTDOJO_PRODUCT_ID}\"
+        }'" DEFECTDOJO_ENGAGEMENT_ID
+  artifacts:
+    paths:
+      - defectdojo-infrastructure.env
+
+defectdojo_upload_trivy_results:
+  stage: upload_results
+  allow_failure: false
+  variables:
+    DEFECTDOJO_SCAN_FILE_DIRECTORY: "./scanresults/trivy/trivy-container-scanning-report.json"
+  script:
+    - source defectdojo-infrastructure.env
     - >
       curl --request POST "${DEFECTDOJO_URL}/import-scan/" \
-            --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
-            --form "scan_date=\"${TODAY}\"" \
-            --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" \
-            --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" \
-            --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" \
-            --form "scan_type=\"${DEFECTDOJO_SCAN_TYPE}\"" \
-            --form "engagement=\"${DEFECTDOJO_ENGAGEMENTID}\"" \
-            --form "file=@${DEFECTDOJO_SCAN_FILE}" \
-            --form "close_old_findings=\"${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}\"" \
-            --form "environment=\"${DEFECTDOJO_SCAN_ENVIRONMENT}\""
+         --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
+         --form "scan_date=\"${TODAY}\"" \
+         --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" \
+         --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" \
+         --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" \
+         --form "scan_type=\"Trivy Scan\"" \
+         --form "engagement=\"${DEFECTDOJO_ENGAGEMENT_ID}\"" \
+         --form "file=@${DEFECTDOJO_SCAN_FILE_DIRECTORY}" \
+         --form "close_old_findings=\"${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}\"" \
+         --form "environment=\"${DEFECTDOJO_SCAN_ENVIRONMENT}\""
+  artifacts:
+    paths:
+      - defectdojo-infrastructure.env
+  dependencies:
+    - defectdojo_create_engagement
